name: Git-shard tests
on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-18.04
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup git
        shell: bash
        run: |
          git config --global user.name "GitShardTester"
          git config --global user.email "GitShardTester@example.com"

      - run: ./test.sh
        shell: bash
